[package]
name = "reth-revm-parallel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "revm parallel execution"

[dependencies]
# reth 
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-provider.workspace = true

# revm
revm = { workspace = true, features = ["optional_beneficiary_reward"] }

# misc
derive_more = "0.99"
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
rayon.workspace = true
num_cpus = "1"
dashmap = "5"
futures.workspace = true
