[package]
name = "reth-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth specific revm utilities"

[dependencies]
# reth
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-provider.workspace = true
reth-consensus-common = { path = "../consensus/common" }
reth-revm-inspectors = { path = "./revm-inspectors" }
reth-revm-parallel = { path = "./revm-parallel", optional = true }

# revm
revm.workspace = true

# common
tracing.workspace = true

[features]
parallel = ["reth-revm-parallel"]